//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L2C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L2C.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 1 \nTest av standardkonstruktorn\n.
        /// </summary>
        internal static string Test1 {
            get {
                return ResourceManager.GetString("Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 2 \nTest av konstruktorn med två parametrar (9, 42)\n.
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 3\n\n.
        /// </summary>
        internal static string Test3 {
            get {
                return ResourceManager.GetString("Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 4\n\n.
        /// </summary>
        internal static string Test4 {
            get {
                return ResourceManager.GetString("Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 5\n\n.
        /// </summary>
        internal static string Test5 {
            get {
                return ResourceManager.GetString("Test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 6 \n\n.
        /// </summary>
        internal static string Test6 {
            get {
                return ResourceManager.GetString("Test6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 7 \n\n.
        /// </summary>
        internal static string Test7 {
            get {
                return ResourceManager.GetString("Test7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 8 \n\n.
        /// </summary>
        internal static string Test8 {
            get {
                return ResourceManager.GetString("Test8", resourceCulture);
            }
        }
    }
}
